pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "hudjo712/ci-cd-demo:latest"
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'b9e3076c-5e67-4eee-97c0-17184f698c47',
                    branch: 'main',
                    url: 'git@github.com:HudJo712/DEVOP1-HudJo712-.git'
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    docker run --rm python:3.9 bash -c "
                    mkdir /app &&
                    echo 'flask\npytest' > /app/requirements.txt &&
                    pip install -r /app/requirements.txt &&
                    echo \\"print('Hello from Docker')\\" > /app/app.py &&
                    python /app/app.py
                    "
                    '''
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('ci-cd-demo') {
                    sh 'docker build -t hudjo712/ci-cd-demo:latest .'
                }
            }
        }


        stage('Push Docker Image') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-creds', url: '']) {
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                docker run --rm -v $HOME/.kube:/root/.kube \
                -v "$PWD/k8s":/k8s \
                bitnami/kubectl:latest apply -f /k8s/deployment.yaml
                '''
            }
        }
    }
}
